[pytest]
markers =
    courses: для тестов, связанных с курсами.
    regression: для регрессионных тестов.
    dashboard: для тестов с рабочей панелью.
    authorization: для тестов с авторизацией.
    registration: для тестов с регистрацией.